// Generated by dts-bundle v0.4.3
// Dependencies for this module:
//   ../../mongodb

declare module 'phoenix-odata' {
    import * as mongodb from 'mongodb';
    export * from 'phoenix-odata/lib/mongodb/connection';
    export var db: {
        connect: (uri: string) => Promise<mongodb.Db>;
        close: (db: mongodb.Db) => Promise<void>;
    };
}

declare module 'phoenix-odata/lib/mongodb/connection' {
    export function connectionString(configMongo: {
        port?: number;
        host?: string;
        user?: string;
        password?: string;
        database?: string;
        options?: any;
    }): string;
}

