// Generated by dts-bundle v0.4.3
// Dependencies for this module:
//   ../../mongodb
//   ../../stream

declare module 'phoenix-odata' {
    import * as mongodb from 'mongodb';
    import * as stream from 'stream';
    export var db: {
        connectionString: (configMongo: {
            port?: number;
            host?: string;
            user?: string;
            password?: string;
            database?: string;
            options?: any;
        }) => string;
        connect: (uri: string) => Promise<mongodb.Db>;
        close: (db: mongodb.Db) => Promise<void>;
    };
    export var schema: {
        createDatabase: (db: mongodb.Db, schemas: any[]) => Promise<void>;
        importCollectionFromFile: (db: mongodb.Db, schema: any, file: string, override: boolean, tenantId?: number) => Promise<void>;
        importCollectionFromStream: (db: mongodb.Db, schema: any, stream: stream.Readable, override: boolean, tenantId?: number) => Promise<void>;
    };
}

