// Generated by dts-bundle v0.4.3

declare module 'phoenix-odata' {
    export * from 'phoenix-odata/lib/mongodb/connection';
}

declare module 'phoenix-odata/lib/mongodb/connection' {
    export function connectionString(configMongo: {
        port?: number;
        host?: string;
        user?: string;
        password?: string;
        database?: string;
        options?: any;
    }): string;
}

